config/routes.rb
Rails.application.routes.draw do
  resources :jobs do
    collection do
      post :import
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  require "csv"

  def self.import(file)
    CSV.foreach(file.path) do |row|
      job = Job.new
      job.type_work = row[0].to_s
      job.department_owner = row[1].to_s
      job.branch_site = row[2].to_s
      job.position = row[8].to_s
      job.number_asset = row[9].to_s
      job.group_asset = row[10].to_s
      job.order_number = row[19].to_i
      job.operation_number = row[20].to_i
      job.operation_description = row[21].to_s
      job.total_plan = row[38].to_i
      job.save
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  def import
    Job.import(params[:file])
    redirect_to jobs_path, notice: "Data imported!"
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.fetch(:job, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<tr>
  <td><%= job.type_work %></td>
  <td><%= job.department_owner %></td>
  <td><%= job.branch_site %></td>
  <td><%= job.position %></td>
  <td><%= job.number_asset %></td>
  <td><%= job.group_asset %></td>
  <td><%= job.order_number %></td>
  <td><%= job.operation_number %></td>
  <td><%= job.operation_description %></td>
  <td><%= job.labor_plain %></td>
  <td><%= job.total_plan %></td>
  <td><%= link_to 'Show', job_path(job) %></td>
  <td><%= link_to 'Edit', edit_job_path(job) %></td>
  <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<h4>import that data!</h4>
<%= form_tag import_jobs_path, multipart: true do %>
<%= file_field_tag :file %>
<%= submit_tag "import CSV" %>
<%end %>

<table>
  <thead>
    <tr>
      <th>type_work</th>
      <th>department_owner</th>
      <th>branch_site</th>
      <th>position</th>
      <th>number_asset</th>
      <th>group_asset</th>
      <th>order_number</th>
      <th>operation_number</th>
      <th>operation_description</th>
      <th>labor_plain</th>
      <th>total_plan</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <%= render @jobs %>


</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UapSpnu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>